project:
  type: website
  output-dir: docs

website:
  title: "a_quarto_website"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: journal
    css: styles.css
    toc: true



